### ISSUE TITLE
Node error running frontend

### ISSUE THREAD

**Issue by steshaw** [tweag/chainsail#456]
## Description

After getting my local development environment running with Minikube, I am trying to get the frontend to start. I am using the provided script:

```sh-session
$ ./run_dev_client.sh
yarn run v1.22.19
$ next dev
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /home/steshaw/Code/tweag/chainsail/app/client/node_modules/next/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at 552 (/home/steshaw/Code/tweag/chainsail/app/client/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11590)
    at __webpack_require__ (/home/steshaw/Code/tweag/chainsail/app/client/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 270 (/home/steshaw/Code/tweag/chainsail/app/client/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:400)
    at __webpack_require__ (/home/steshaw/Code/tweag/chainsail/app/client/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 327 (/home/steshaw/Code/tweag/chainsail/app/client/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
    at __webpack_require__ (/home/steshaw/Code/tweag/chainsail/app/client/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 845 (/home/steshaw/Code/tweag/chainsail/app/client/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3733) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce

1. Get the service running in Minikube via https://github.com/tweag/chainsail/blob/main/docs/deployment.md#initial-setup.
2. `cd ./app/client`
3. `yarn`
4. `./run_dev_client.sh`

## Expected behavior

The frontend starts.

**Environment**
 - OS: Ubuntu 22.04.2 LTS
 - Version of the code: Branch `main` at 2d26ae0ee4f9565917a2f3fd795eca3f63c0226a.

**Additional context**

Nothing.

**Comment by simeoncarstens** [comment]
See #449 :wink: but I didn't remember either that I had opened an issue about that.

**Comment by steshaw** [comment]
Snap 😄! Closing as duplicate.
